# Generated by Django 4.2.5 on 2024-02-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Station', 'Station'), ('Employee', 'Employee'), ('Customer', 'Customer')], default='Customer', max_length=50),
        ),
    ]
