# Generated by Django 4.2.5 on 2024-02-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('maintenance_record', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=100)),
                ('equipment_inventory', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team_incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.employee')),
                ('equipments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.equipment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('assigned_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.team_incident')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.customer')),
            ],
        ),
    ]
