# Generated by Django 4.2.5 on 2024-02-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0005_rename_team_incident_team_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_assign',
            name='employee',
        ),
        migrations.AlterField(
            model_name='team_assign',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.incident'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employees', models.ManyToManyField(to='stationapi.employee')),
            ],
        ),
        migrations.AddField(
            model_name='team_assign',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stationapi.team'),
        ),
    ]
