# Generated by Django 4.2.5 on 2024-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0006_remove_team_assign_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_logged',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
