# Generated by Django 4.2.5 on 2024-02-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0007_customer_last_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
