# Generated by Django 4.2.5 on 2024-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0008_guest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Station', 'Station'), ('Employee', 'Employee'), ('User', 'User')], default='User', max_length=50),
        ),
    ]
