# Generated by Django 4.2.5 on 2024-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0009_rename_customer_user_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='equipment_inventory',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='equipment_inventory',
            field=models.ManyToManyField(to='stationapi.equipment'),
        ),
    ]
