# Generated by Django 4.2.5 on 2024-02-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0014_alter_training_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[('Alerted', 'Alerted'), ('Saved', 'Saved'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Alerted', max_length=50)),
                ('Incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.incident')),
            ],
        ),
    ]
