# Generated by Django 4.2.5 on 2024-02-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0015_incidentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatus',
            name='status',
            field=models.CharField(choices=[('Alerted', 'Alerted'), ('Saved', 'Saved'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Alerted', max_length=50),
        ),
    ]
