# Generated by Django 4.2.5 on 2024-03-02 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0016_alter_incidentstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.employee'),
        ),
    ]
