# Generated by Django 4.2.5 on 2024-03-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0017_alter_training_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
