# Generated by Django 4.2.5 on 2024-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0018_alter_station_email_address_alter_station_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
