# Generated by Django 4.2.5 on 2024-03-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0019_alter_employee_email_address_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stationapi.user'),
        ),
    ]
