# Generated by Django 4.2.5 on 2024-03-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0020_incident_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='equipment_inventory',
        ),
    ]
