# Generated by Django 4.2.5 on 2024-03-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0021_remove_vehicle_equipment_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_assign',
            name='equipments',
        ),
        migrations.RemoveField(
            model_name='team_assign',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='incidentstatus',
            name='Incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.incident', unique=True),
        ),
    ]
