# Generated by Django 4.2.5 on 2024-03-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0022_remove_team_assign_equipments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_assign',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.incident', unique=True),
        ),
        migrations.AlterField(
            model_name='team_assign',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationapi.team'),
        ),
    ]
