# Generated by Django 4.2.5 on 2024-03-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0023_alter_team_assign_incident_alter_team_assign_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_assign',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stationapi.incident'),
        ),
    ]
