# Generated by Django 4.2.5 on 2024-03-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0024_alter_team_assign_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatus',
            name='Incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stationapi.incident'),
        ),
    ]
