# Generated by Django 4.2.5 on 2024-03-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationapi', '0025_alter_incidentstatus_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
